### ISSUE TITLE
Unclear dependencies and privacy requirements

### ISSUE THREAD

**Issue by RocketSloooth** [TheITguy21/check_speedtest.sh#2]
Hi,

I do not know your level of affiliation with Ookla, but wanted to provide some constructive feedback on why I have decided to NOT install this package at this point in time, in case you are interested in making any improvements.

And to be clear, assuming you have no direct relationship with Ookla, my decision is solely based on the installation procedure for Ookla's `speedtest` package, which you list as a dependency for your Nagios script.

I went and checked the Ookla web page and looked at the installation instructions for Ubuntu systems, which look like:
`$ sudo apt-get install curl`
`$ curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash`
`$ sudo apt-get install speedtest`

I am not a security expert, but I am wary of running any command that auto-executes a downloaded shell script, so I downloaded the `script.deb.sh` file and looked into it.

The script does a number of things, which may or may not be desirable by the user.
Amongst others:
- it runs the `$ apt-get update` command;
- it installs the `curl` package - this is odd because the first line of the installation instructions already does that;
- it installs the `gnupg` package;
- it installs the `debian-archive-keyring` package;
- it installs the `apt-trasport-https` package;
- it creates a debian repository configuration file in `/etc/apt/sources.list.d/ookla_speedtest-cli` downloading from https://packagecloud.io/install/repositories/ookla/speedtest-cli/config_file.list?os=${os}&dist=${dist}&source=script (after populating the `${os}` and `${dist}` variables) - this configuration file points to the https://packagecloud.io/ookla/speedtest-cli/debian/ location, which is non browseable;
- it creates a GPG keyring and imports keys from https://packagecloud.io/ookla/speedtest-cli/gpgkey into a directory of trusted keyrings for the `apt` command;
- it runs the `$ apt-get update` command again and exits.

At this stage the last line of the original installation instructions will effectively install the `speedtest` package onto the system.

The issue I have with this approach is that it's needlessly convoluted and obscure, and it required me to parse the script just to understand what it does, whereas a simple and transparent approach would just be to list all dependencies and clearly highlight that the `speedtest` package is installed from a third party private repository.

Since you already list `bc` as a dependency, may I suggest that you either list the other packages that the Ookla script installs as requirements, or share more info on what the Ookla `speedtest` installation procedure requires?

I completely understand that if you are not affiliated with Ookla you would not be able to keep up with their changes (which is why I think you just listed their package as a dependency), but you could improve your documentation by making your users aware of what they are getting into.

As a last comment, the final reason why I decided to not go ahead with this script is Ookla's privacy policy.

They offer the option to download a standalone `speedtest` executable, which I did.

The first thing that happens when running the executable is that you as the user are requested to accept a EULA, T&Cs and a Privacy policy.

Nothing unusual so far, however in the privacy policy Ookla discloses that they collect PII data which they then are intending to share with "internet providers, hardware manufacturers and industry regulators". Which basically means that Ookla resells user data to third parties.

Ookla is offering a free service, and therefore they have all the rights to monetise it however they like, either to recover the costs or to make a profit. However, I think it would be fairer to your user if you gave them a heads up on this being part of the deal when satisfying the requirements for your Nagios script.

All in all, while I cannot comment on your script because I haven't tested it, I appreciate you spending the time to put this together and offering an alternative to the original `check_speedtest-cli.sh` script.

I just hope that you can find the time to add some clarification in your documentation based on my comments above.

Cheers!

**Comment by TheITguy21** [comment]
Hi,

Thank you very much for your feedback ! First, I am not affiliated with Ookla in any ways indeed. I'm just a geek who wrote this script for my personal servers at home, and thought this could benefit to other 😊

When a published this, I must confess I thought "everyone should know what they're doing", including installing dependencies and dealing with it. But I really appreciate your concern about all what you raised, which is totally relevant, and the time you took to let me know.

I've updated the README file to provide more warning about all this, please let me know if this is acceptable to you 😉

Cheers

**Comment by RocketSloooth** [comment]
Hello again :)

Thank you for your follow-up, I am glad that you took my feedback constructively, as it was intended.

You are right that "everyone should know what they're doing" but you would be surprised how many people just go ahead and execute scripts downloaded from the web without a second thought ;)

I think your README is much more comprehensive now - again, thank you for following up on my feedback.

Also, once more thank you for investing your time to make this Nagios configuration available to others!

All the best!
