### ISSUE TITLE
Plugin returns No output

### ISSUE THREAD

**Issue by richardturnerfos** [TheITguy21/check_speedtest.sh#4]
Hi - having issues getting the plugin to work.

Nagios 4.4.2
Plugin: 1.0 2023031814:30

If I run the check manually It works : 
```
/usr/local/nagios/libexec/check_speedtest -w 7 -c 5 -W 7 -C 5 
OK - Ping = 7.34 ms Download = 93.04 Mbps Upload = 93.18 Mbps
```
If I run this as the nagios user, the same result. If I run it as a plugin get No output. 

If I add the -V switch, the output looks like

```
[1701856267.946754] [016.1] [pid=27864]  * OPTIONS: 0, SCHEDULED: 1, RESCHEDULE: 1, EXITED OK: 1, RETURN CODE: 3, OUTPUT:
Download Warning Level = 7
Download Critical Level = 5
Upload Warning Level = 7
Upload Critical Level = 5
No specific target server defined


[1701856267.946821] [001.0] [pid=27864] get_service_check_return_code()
```
showing that text is being produced by the plugin, but no result.

Any thoughts?

**Comment by TheITguy21** [comment]
Hi, I'm not sure why the verbose return the error "No specific target server defined" 🤔
Try to specify a server : 
- List speedtest available servers running this command : "`speedtest --servers`"
![image](https://github.com/TheITguy21/check_speedtest.sh/assets/127893834/fb572c9f-d1fa-4311-ab85-2a35c7da1baa)
- Pick a server ID from the results, and update your plugin conf so the server you want to test against is spcified

Here's how it's configured on my centreon : 
- The command is declared like this : 
![image](https://github.com/TheITguy21/check_speedtest.sh/assets/127893834/eee2d738-b461-4f5b-b37b-57aaf3211a32)
- The plugin arguments are like this. Notice $ARG7 (other arguments) contains "-s 23884" in my case
![image](https://github.com/TheITguy21/check_speedtest.sh/assets/127893834/b0fe00d0-f948-43dc-9106-c327d08c1a01)

So the final command executed by the plugin is this one : 
![image](https://github.com/TheITguy21/check_speedtest.sh/assets/127893834/d242a0dc-6bd7-4829-b0c1-ba52ef7d5622)

I've tried without specify a specific server ID, it works for me. I'm using Centreon.

I hope you'll find out ! ☺

**Comment by richardturnerfos** [comment]
Thanks for the quick reply.

Lots of attempts later - It's the speedtest client.  If I run it manually or through your script it works. If I the plugin through nagios it crashes/dumps and there is a apport log written. Possibly something in the "nagios" user environment when it calls the code. e. 

```
executable: /usr/bin/speedtest (command line "/usr/bin/speedtest --accept-gdpr --accept-license --progress=yes --server-id=25119")
ERROR: apport:  is_closing_session(): no DBUS_SESSION_BUS_ADDRESS in environment
ERROR: apport: wrote report /var/crash/_usr_bin_speedtest.1001.crash
```

The error message for that indicate it fails is commented out, and it was working manually so didn't look at that failing initially. I suppose it could be down to the ubuntu still being v16??  I'll need to try on a newer server (good excuse to upgrade) or contact Ookla Support.
