### ISSUE TITLE
Plugin not compatible with current speedtest cli under Debian/Ubuntu 11

### ISSUE THREAD

**Issue by strfl89** [TheITguy21/check_speedtest.sh#5]
Installed the speedtest-cli from ookla with the script on a RaspberryPi with Debian / Raspian 11 and detected the following issues:

1. the following parameters are no longer available: `--accept-gdpr --accept-license --progress=no` (Lines 310, 315, 317)
2. the output of a speedtest didn't contains `Speedtest by Ookla` (Line 322)
3. the Extract/parse values from output didn't work (Lines 336 - 341)

Here is a sample Output what I receive 
```
./check_speedtest.sh -w 40 -c 35 -W 18 -C 15 -V
Download Warning Level = 40
Download Critical Level = 35
Upload Warning Level = 18
Upload Critical Level = 15
No specific target server defined
Command output:
Retrieving speedtest.net configuration...
Testing from Vodafone Germany DSL (XXX.XXX.XXX.XXX)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by LWLcom GmbH (Frankfurt) [3.12 km]: 13.66 ms
Testing download speed................................................................................
Download: 57.06 Mbit/s
Testing upload speed......................................................................................................
Upload: 24.43 Mbit/s
Extracted values:
Ping = 
Download = Download: 57.06 Mbit/s
Upload = Upload: 24.43 Mbit/s
Everything within bounds!
OK - Ping = Download = Download: 57.06 Mbit/s Download: 57.06 Mbit/s Upload = Upload: 24.43 Mbit/s Upload: 24.43 Mbit/s
```

Tried to fix it on my own, but I'm not able to build the ne working regex for lines 336 - 341.

**Comment by TheITguy21** [comment]
Hi ! Thanks for you feedback 🙂 Here's my answers to your points : 

1. "_the following parameters are no longer available_"
I don't know why people keep saying this to me 😀 Here's the output results (first launch), without and with those parameters : 

- Without
![image](https://github.com/TheITguy21/check_speedtest.sh/assets/127893834/95e7d1d8-4816-4470-bef0-e1383f227908)

- With
![image](https://github.com/TheITguy21/check_speedtest.sh/assets/127893834/1f24399a-63b7-42ee-a970-001f67eadb17)

About `--progress=no` : 

- Without
![image](https://github.com/TheITguy21/check_speedtest.sh/assets/127893834/f7ee0e3e-67c5-4549-8359-687247d0e0f3)

- With
![image](https://github.com/TheITguy21/check_speedtest.sh/assets/127893834/4677d87b-84a1-4e8e-868e-1967e9a16c2a)

I'm not sure what's the benefit to NOT show progress anyway, I thought it would be unnecessary when using only the final values for Nagios/Centreon plugin 😁

2. "_the output of a speedtest didn't contains Speedtest by Ookla_"
Here's the output when I execute `speedtest` : 
![image](https://github.com/TheITguy21/check_speedtest.sh/assets/127893834/af4b63c7-4d8b-4f30-9e9e-b18eeeeedb6e)
Note : I'm not sure why this error "`Timeout occured in connect`", it wasn't there before. I guess it's a bug in their latest release as I don't remember this error was shown before 🤷🏻‍♂️

3. "_the Extract/parse values from output didn't work_"
I'm not sure what you mean. Here's my output : 
![image](https://github.com/TheITguy21/check_speedtest.sh/assets/127893834/309e9457-7922-4c7a-a600-08595ef3b152)
Can you run `# speedtest --accept-gdpr --accept-license` on your machine and post the raw output here so I can figure out ?

Thanks

**Comment by strfl89** [comment]
here is a screenshot how it looks like on my Raspbian 11 system

<img width="682" alt="image" src="https://github.com/TheITguy21/check_speedtest.sh/assets/16718515/ada94294-fb51-49c5-9d5b-36f8fe2ca2a7">

**Comment by TheITguy21** [comment]
Oh, weird 🤔 Can you confirm you've installed speedtest as explained here [https://www.speedtest.net/apps/cli](https://www.speedtest.net/apps/cli) for Ubuntu/debian ?
Also make sure you've followed their instructions if they apply to you (in the yellow rectangle)
![image](https://github.com/TheITguy21/check_speedtest.sh/assets/127893834/b908e650-8240-4790-b573-5ee30f67f83b)

If you did all right, I'm affraid I won't be able to help, I guess those variants/differences must be specific to Raspbian ?
Sorry 🤷🏻‍♂️

**Comment by strfl89** [comment]
Upgraded the system to Raspbian 12 (bookworm) and make a fresh speedtest installation.

the script wich is provided by ookla is not optimized for raspbian and must be started wir the following parameters:
`os=debian dist=bookworm`

Now the Speedtest Results looks like your screenshots @TheITguy21 and the script is working as expected.
