### ISSUE TITLE
Switches are ignored

### ISSUE THREAD

**Issue by Kami-71** [TheITguy21/check_speedtest.sh#6]
When i use 
`./check_speedtest.sh -w 80 -c 40 -W 4 -C 2 -p -V`
I keep getting the standard output of the script. 
![2024-03-22 06_18_05-](https://github.com/TheITguy21/check_speedtest.sh/assets/107390720/ca4907b3-5dc2-4c9a-ab6f-1292a0bf5ceb)
Am I doing something wrong?

The speedtest from oOkla itself is running.

**Comment by TheITguy21** [comment]
![image](https://github.com/TheITguy21/check_speedtest.sh/assets/127893834/0f160302-8f64-4f22-a4dd-abdbc136a785)
