### ISSUE TITLE
is there an issue with the ookla repo being empty?  

### ISSUE THREAD

**Issue by joev-mi** [TheITguy21/check_speedtest.sh#8]
I realize you do not work for nor are responsible for what ookla posts but I thought if you happened to have any insight that would be great.  I ran the two commands for the fedora context as ookla recommends.  It prompted me to accept the signatures and created the two repos in one file as below, however, when I interrogate the repo it shows no applications offered, specifically it does not have speedtest.  (Note: I took a quick look at the ookla site for a support link but it wasn't immediately obvious, perhaps I merely need to be more diligent in that direction.)

####  my copy of ookla_speedtest-cli.repo
[ookla_speedtest-cli]
name=ookla_speedtest-cli
baseurl=https://packagecloud.io/ookla/speedtest-cli/fedora/39/$basearch
repo_gpgcheck=1
gpgcheck=0
enabled=1
gpgkey=https://packagecloud.io/ookla/speedtest-cli/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300

[ookla_speedtest-cli-source]
name=ookla_speedtest-cli-source
baseurl=https://packagecloud.io/ookla/speedtest-cli/fedora/39/SRPMS
repo_gpgcheck=1
gpgcheck=0
enabled=1
gpgkey=https://packagecloud.io/ookla/speedtest-cli/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300

**Comment by TheITguy21** [comment]
Sorry, I don't provide any support outside the script perimeter, I don't know anything about Fedora 😅

**Comment by joev-mi** [comment]
... and I'm looking forward to ironing out the last kinks here.  I did
find the support link at ookla and opened a ticket.

--
regards,

Joe Verreau
Okemos, MI
- - - - - - -
